### PR TITLE
Move build configuration into package.json

### PR DESCRIPTION
**Pull request by rikukissa**
What do you think @cheapsteak @tjyrkinen ? Another option would be to create config.json, but I prefer having just one json file to describe the project's structure.

### CODE REVIEW

**Comment by cheapsteak** [comment]
I like it
btw you accidentally included react in the dependencies

**Comment by rikukissa** [comment]
Good catch! I started wondering if there's a use case where you'd want to define paths programmatically and now couldn't because it's in a JSON file..

**Comment by cheapsteak** [comment]
That's a good point  

To be honest I haven't run into a situation that's really needed dynamic paths

One use case that's maybe kind of similar is being able to specify a different name for the `public` folder - for my projects I usually manually change each instance of the `public` folder to the `build` folder (only the files inside that folder gets deployed). It would be convenient to be able to specify the name of the folder in one place and have the rest of the `destination`s use that variable

**Comment by rikukissa** [comment]
I'm usually renaming it to "dist" myself and have thought about that too. Maybe we could change it so that the "source" and "destination" properties would be prefixes for all the other paths. For example the "scripts" block would become something like this

```diff
"scripts":{
-   "source":"./src/main.js",
-   "destination":"./public/js/",
+   "source":"main.js",
+   "destination":"js/",
  "extensions":[],
  "filename":"bundle.js"
},
```

**Comment by cheapsteak** [comment]
That would be perfect!

**Comment by cheapsteak** [comment]
Just thought of potential problem with how that affects the npm scripts  

```
"start": "rm -rf public && gulp",
```

how do we pass that in?

**Comment by rikukissa** [comment]
Good point... We pretty much have that problem now too, because if you change the public directory to "dist" for example you'll have to change it from the scripts too. This pull request would at least move the config to the same file with the scripts making it more noticeable. Since there's really no way to read the config in the script configuration, we'll probably have to do the initial removal in the gulpfile.

By prefixing all paths with "source" and "destination" paths, we could also be introducing unnecessary complexity to our gulpfile. It also might make the configuration less flexible. I see no reason why we shouldn't merge this pull request, but I think we shouldn't prefix the paths automatically.

**Comment by cheapsteak** [comment]
the react dependency is currently still in there, but otherwise I think it'd be good to merge as well :)

**Comment by rikukissa** [comment]
thanks for reminding!

**Pull request merged**
